version: "3"

services:
  app:
    image: magento/nginx:1.18
    ports:
      - 80:8000
      - 443:8443
    external_links:
      - db
      - phpfpm
      - phpcron
    depends_on:
      - phpfpm
      - phpcron
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs
    environment:
      - UPLOAD_MAX_FILESIZE=32M
      - FPM_HOST=phpfpm
      - FPM_PORT=9000
      - CRON_HOST=phpcron
      - CRON_PORT=9000
      - MAGENTO_ROOT=/var/www/html
      # - VIRTUAL_HOST=magento2.docker
      # - VIRTUAL_PORT=80
      # - HTTPS_METHOD=noredirect
  phpfpm:
    image: magento/php:7.4
    ports:
      - 9090:9000
    env_file: 
      - env/magento.env
      - env/db.env
    external_links:
      - db
      - elasticsearch
      - rabbitmq
      - redis
      - varnish
    volumes: *appvolumes
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
  # In a multi-node system, crontab can run on only one node.
  phpcron:
    image: magento/php:7.4
    ports:
      - 9091:9000
    env_file: 
      - env/magento.env
      - env/db.env
    external_links:
      - db
      - elasticsearch
      - rabbitmq
      - redis
      - varnish
    volumes: *appvolumes
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - CRON=on

volumes:
  appdata:
  sockdata:
  ssldata:
