version: "3"

services:
  varnish:
    image: magento/varnish:6.0
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=80
      - HTTPS_METHOD=noredirect
    ports:
      - 8080:80
    external_links:
      - app
  db:
    image: mysql:5.7
    command: --max_allowed_packet=64M
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
      - dbconfig:/etc/mysql/conf.d
      - dblog:/var/log/mysql
  redis:
    image: redis:5.0-alpine
    command: redis-server --appendonly yes --requirepass magento
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  elasticsearch:
    image: magento/elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.6.2
    external_links:
      - elasticsearch:es
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
      ELASTICSEARCH_SSL_VERIFICATIONMODE: none
    ports:
      - 5601:5601
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - mqdata:/var/lib/rabbitmq

volumes:
  dbdata:
  dbconfig:
  dblog:
  redisdata:
  esdata:
  mqdata:
